name: ee
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - earthengine-api
  - py6s
  - geemap
  - seaborn
  - scipy
  - pip
  - pip:
    - pandas~=1.3.3
    - parse==1.19.0
    - git+https://github.com/luislizcano/gee-atmcorr-py6s.git
